# This file was generated by GoReleaser. DO NOT EDIT.
cask "suri" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "71944251ac7b54036f50ea8517a28a6a290674edf23fddd7ff0a0655f0c3abd0"
      url "https://github.com/osintph/suri/releases/download/v#{version}/suri_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "afad9853889164fda774a78266b65d5e12885deec54ad364f9b686e4388effde"
      url "https://github.com/osintph/suri/releases/download/v#{version}/suri_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c7b272364cd2b971933de66c47735c2b6067071252484243da6d45f7a448619a"
      url "https://github.com/osintph/suri/releases/download/v#{version}/suri_#{version}_linux_arm64.tar.gz"
    end
  end

  name "suri"
  desc "Web application security scanner for authorized VAPT engagements"
  homepage "https://github.com/osintph/suri"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "suri"

  # No zap stanza required

end
