# This file was generated by GoReleaser. DO NOT EDIT.
cask "suri" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "678d23f463705ae47e0b6445be9b64ec1636021e38755d413957b0205fb44e29"
      url "https://github.com/osintph/suri/releases/download/v#{version}/suri_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a10b802f2feca724728e6686fa476d48770e8296612b61305170fda94f50a257"
      url "https://github.com/osintph/suri/releases/download/v#{version}/suri_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ecc7f786d008ef41ff42b742968a9224eee06e6e0e4611f6312eb25b4ef248a4"
      url "https://github.com/osintph/suri/releases/download/v#{version}/suri_#{version}_linux_arm64.tar.gz"
    end
  end

  name "suri"
  desc "Web application security scanner for authorized VAPT engagements"
  homepage "https://github.com/osintph/suri"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "suri"

  # No zap stanza required

end
