# This file was generated by GoReleaser. DO NOT EDIT.
cask "suri" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "1a56f1bdb901a74a77f2b97c5b03693802a4c7c499a0f31a86ba291f93dfe33b"
      url "https://github.com/osintph/suri/releases/download/v#{version}/suri_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "61f0e80590fc406db68170b0c9987c0d53eb11dee1c40daf7e86362681a19eeb"
      url "https://github.com/osintph/suri/releases/download/v#{version}/suri_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c7cb80b3bc641576c523fa7e580d8bd0fa38d4760486ec2554f3955d7d8ac14"
      url "https://github.com/osintph/suri/releases/download/v#{version}/suri_#{version}_linux_arm64.tar.gz"
    end
  end

  name "suri"
  desc "Web application security scanner for authorized VAPT engagements"
  homepage "https://github.com/osintph/suri"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "suri"

  # No zap stanza required

end
